# Generated by Django 5.2.7 on 2025-11-02 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.PositiveIntegerField(max_length=20, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('font', models.CharField(blank=True, max_length=100, null=True)),
                ('text_color', models.PositiveSmallIntegerField(choices=[(1, 'white'), (2, 'yellow'), (3, 'blue'), (4, 'black')], default=1, verbose_name='text color')),
                ('shirt_color', models.PositiveSmallIntegerField(choices=[(1, 'white'), (2, 'yellow'), (3, 'blue'), (4, 'black')], default=4, verbose_name='shirt color')),
                ('image', models.ImageField(upload_to='mockups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gen_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='mockups.generationtask')),
            ],
        ),
    ]
