# Generated by Django 5.2.7 on 2025-11-02 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationtask',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
