# Generated by Django 5.2.7 on 2025-11-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0002_alter_generationtask_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockup',
            name='gen_task',
        ),
        migrations.AddField(
            model_name='mockup',
            name='task_id',
            field=models.CharField(db_index=True, default='import uuid; uuid.uuid4().hex', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GenerationTask',
        ),
    ]
