# Generated by Django 5.2.7 on 2025-11-25 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0003_remove_mockup_gen_task_mockup_task_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('font', models.FileField(upload_to='fonts/')),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('existence', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='shirts/')),
            ],
        ),
        migrations.AddField(
            model_name='mockup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='text_color',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mockups.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='font',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='mockups.font', verbose_name='Font'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mockup',
            name='shirt_color',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mockups.shirt', verbose_name='Shirt'),
        ),
    ]
