# Generated by Django 5.2.7 on 2025-11-28 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0004_color_font_shirt_mockup_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex',
            field=models.CharField(default=0, max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mockup',
            name='font',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mockups.font', verbose_name='Font'),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='shirt_color',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mockups.shirt', verbose_name='Shirt'),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='text_color',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mockups.color', verbose_name='Color'),
        ),
    ]
